app:
  protocol: http
  host: 127.0.0.1
  version: v1


api:
  data:
    port: 9191
    baseUrl: ${app.protocol}://${app.host}:${api.data.port}
#     prefix: ${app.protocol}://${app.host}:${api.data.port}/data/
    user: ${api.data.baseUrl}/data/${app.version}/users
    userByEmail: /email
